apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: acaisoft-frontend
    spec:
      containers:
      - name: careercon-frontend
        image: acaisoft/careercon-frontend
        ports:
        - name: frontend-port
          containerPort: 8000