apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - nodePort: 31001
    port: 80
    protocol: TCP
    targetPort: backed-port
  selector:
    run: acaisoft-backend
  sessionAffinity: None
  type: LoadBalancer