apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - nodePort: 31001
    port: 31001
    protocol: TCP
    targetPort: 8000
  selector:
    app: acaisoft-backend
  sessionAffinity: None
  type: NodePort