apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
  - nodePort: 31002
    port: 80
    protocol: TCP
    targetPort: frontend-port
  selector:
    run: acaisoft-frontend
  sessionAffinity: None
  type: LoadBalancer
